project:
  type: website
  output-dir: docs

website:
  title: "school_tool"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: ratio1.qmd
        text: อัตราส่วนครั้งที่ 1
      - href: first_ojs.qmd
        text: ojs
      - href: test_scrolling.qmd
        text: scrolling telling
  reader-mode: true
  back-to-top-navigation: true

format:
  html:
    theme:
      light: flatly
      dark:  darkly
    css: styles.css
    toc: true
    page-layout: full
    grid: 
      margin-width: 300px
    smooth-scroll: true



