project:
  type: website
  output-dir: docs

website:
  title: "school_tool"
  sidebar:
    style: floating
    contents:
      - href: index.qmd
        section: Home
        contents: 
          - href: test_scrolling.qmd
            text: scrolling telling
          - href: test_scrolling2.qmd
            text: กราฟและความสัมพันธ์เชิงเส้น
          - href: first_ojs.qmd
            text: ojs
      - href: about.qmd
        section: About
        contents: 
          - href: first_ojs.qmd
            text: ojs
  reader-mode: true
  back-to-top-navigation: true

format:
  html:
    theme:
      light: flatly
      dark:  darkly
    css: styles.css
    toc: true
    page-layout: full
    grid: 
      margin-width: 300px
    smooth-scroll: true



